services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Dashboard/backend:/Dashboard/backend
    depends_on:
      - mysql
    env_file:
      - .env

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./Dashboard/frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
